kind: Service #Services provide discovery and routing between pods
apiVersion: v1
metadata:
  name: springboot-k8s-mysql
  labels: #specify identifying attributes of objects that are meaningful and relevant to users
    name: springboot-k8s-mysql
spec:
  ports:
    - nodePort: 30163 #get external traffic directly to your service.
      port: 8080      
      targetPort: 8080  
      protocol: TCP
  selector:           
    app: springboot-k8s-mysql
  type: NodePort       

---
apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: springboot-k8s-mysql
spec:                
  selector:         
    matchLabels:
      app: springboot-k8s-mysql
  replicas: 3        
  template:
    metadata:
      labels:        
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: springboot-k8s-mysql
          image: prathm6601/k8mysql:spring
          ports:
            - containerPort: 8080                
          env:   #set env for database
          - name: DB_HOST   # Setting Database host address from configMap
            valueFrom: 
              configMapKeyRef:
                name: db-conf  # name of configMap
                key: host
          - name: DB_NAME  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf 
                key: name
          - name: DB_USERNAME  # Setting Database username from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials # Secret Name
                key: username
          - name: DB_PASSWORD # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password     
        
