kind: Service #expose applications both internally and externally.
apiVersion: v1
metadata:
  name: springboot-k8s-mysql
  labels: #used to specify identifying attributes of objects that are meaningful and relevant to users,
    name: springboot-k8s-mysql
spec:
  ports:
    - nodePort: 30163 #external access to your applications range 30000-32767
      port: 8080      
      targetPort: 8080  
      protocol: TCP
  selector:      #identify a set of objects.      
    app: springboot-k8s-mysql
  type: NodePort       

---
apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: springboot-k8s-mysql
spec:                
  selector:  #identify a set of objects.        
    matchLabels:
      app: springboot-k8s-mysql
  replicas: 3        
  template:
    metadata:
      labels:        
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: springboot-k8s-mysql
          image: prathm6601/k8mysql:spring
          ports:
            - containerPort: 8080                
          env:  
          - name: DB_HOST 
            valueFrom: 
              configMapKeyRef:
                name: db-conf 
                key: host
          - name: DB_NAME 
            valueFrom:
              configMapKeyRef:
                name: db-conf 
                key: name
          - name: DB_USERNAME 
            valueFrom:
              secretKeyRef:
                name: db-credentials 
                key: username
          - name: DB_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password     
        
